env:
    browser: true
    es6: true
extends:
    - "eslint:recommended"
    - "plugin:react/recommended"
    - "prettier"
parserOptions:
    ecmaVersion: 2021
    sourceType: module
    ecmaFeatures:
        jsx: true
rules:
    no-unused-vars:
        - error
        - args: none
