env:
    browser: true
    es6: true
plugins:
  - "jest"
extends:
    - "eslint:recommended"
    - "plugin:jest/recommended"
    - "plugin:react/recommended"
    - "prettier"
parserOptions:
    ecmaVersion: 2021
    sourceType: module
    ecmaFeatures:
        jsx: true
rules:
    no-unused-vars:
        - error
        - args: none
    "react/react-in-jsx-scope":
        - off
