version: '3.1'

services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypass

  mongo-express:
    container_name: mongodb-admin
    image: mongo-express
    restart: always
    ports:
      - 9090:9090
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypass
      ME_CONFIG_MONGODB_URL: mongodb://root:mypass@mongo:27017/