version: '3.1'

services:
  mongodb:
    container_name: chirp-mongodb
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - "./db:/usr/app/dev"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypass

  chirp-server:
    build: server
    container_name: chirp-server
    command: yarn start:docker
    ports:
      - 4000:4000
    volumes:
      - "./server/src:/usr/app/src"
    depends_on:
      - mongodb

  chirp-client:
    build: client
    container_name: chirp-client
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - "./client/src:/usr/app/src"
      - "./client/public:/usr/app/public"
    depends_on:
      - chirp-server
    