env:
    node: true
    es6: true
extends:
    - "eslint:recommended"
    - "prettier"
parserOptions:
    ecmaVersion: 2021
    sourceType: module
rules:
    no-unused-vars:
        - error
        - args: none